apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm/reports-server/charts/reports-server
  contents:
  - path: .
    git:
      url: https://github.com/giantswarm/reports-server-upstream
      ref: reports-server-chart-0.1.0-alpha.1
    includePaths:
      - charts/reports-server/**/*
    newRootPath: charts/reports-server
