name: reports-server

image:
  registry: gsoci.azurecr.io
  name: giantswarm/reports-server
  pullPolicy: IfNotPresent
  # Default tag is the chart appVersion, if not set here.
  tag: ""

reports-server:
  image:
    registry: gsoci.azurecr.io
    repository: giantswarm/reports-server
    pullPolicy: IfNotPresent
    # Default tag is the chart appVersion, if not set here.
    tag: ""
  postgresql:
    enabled: false  # A PostgreSQL cluster is deployed using CNPG resources, defined below.
  apiServices:
    enabled: false
  config:
    debug: false
    db:
      secretName: "reports-server-app"

postgres:
  cnpg:
    enabled: true
    instances: 2
    storage:
      size: 1Gi
    monitoring:
      grafanaDashboard:
        enabled: true
      podMonitor:
        enabled: true
        labels: {}
    imageCatalogRef:
      major: 16
      name: gs-postgresql
    switchoverDelay: 60
