name: reports-server
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/reports-server
  tag: v0.0.1
  pullPolicy: IfNotPresent
