name: reports-server

image:
  registry: gsoci.azurecr.io
  name: giantswarm/reports-server
  pullPolicy: IfNotPresent
  # Default tag is the chart appVersion, if not set here.
  tag: ""

reports-server:
  postgresql:
    enabled: false
  apiServices:
    enabled: false
