{{- if .Values.postgres.cnpg.enabled -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "reports-server.fullname" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  instances: {{ .Values.postgres.cnpg.instances }}

  storage:
    size: {{ .Values.postgres.cnpg.storage.size }}
{{- end -}}
