{{- if .Values.postgres.cnpg.enabled -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "reports-server.fullname" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  instances: {{ .Values.postgres.cnpg.instances }}

  storage:
    size: {{ .Values.postgres.cnpg.storage.size }}

  monitoring:
    enablePodMonitor: {{ .Values.postgres.cnpg.monitoring.podMonitor.enable }}
    podMonitorAdditionalLabels:
    {{- with .Values.monitoring.podMonitorAdditionalLabels }}
    {{- toYaml . | nindent 6 }}
    {{- end}}
    grafanaDashboard:
      create: {{ .Values.postgres.cnpg.monitoring.grafanaDashboard.enable }}
{{- end -}}
